- name: Instalação do Java
  hosts: meu_pc
  tasks:
  - name: "instala pacote wget ubuntu"
    ansible.builtin.apt:
      name: wget, git, curl, cmatrix
      state: present
      update_cache: yes
    #when: (ansible_facts['distribution'] == "Ubuntu")